### ISSUE TITLE
How to create MirroringData asset?

### ISSUE THREAD

**Issue by horatiu665** [mamemame360/AnimMirroring#1]
I installed the plugin with some effort - it was my first plugin - had to install .NET core 3.1, put it in new project made with c++ and the build the generated solution, and now I can access the Mirror node in the animation blueprint. 

However I am stuck how to create a MirroringData object - it's a custom type of asset I suppose, but I can't find anywhere how to create such an asset, to add to the settings of the node. Can you help?
![image](https://user-images.githubusercontent.com/5824753/127145005-85afbe7e-cd83-4393-8ea9-3f4dde111524.png)

**Comment by mamemame360** [comment]
Hi @horatiu665.
Thanks for your report.

It looks like there have been some changes since 4.25. (I had only maintained it up to 4.24).
I will try to fix it.

https://answers.unrealengine.com/questions/969157/ue425-factorycreatenew-dont-work.html

**Comment by mamemame360** [comment]
@horatiu665
It should been solved, could you try again?

**Comment by horatiu665** [comment]
hi! thanks for the super fast reply and the fix. I didn't see it and I don't have a chance to try again in the near future, but I'll keep this in mind when I'm back to work on this stuff. Hopefully someone else confirms if it works meanwhile.
